
version: '2'

services:
  stickerapp:
    image: stickerapp:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      MONGODB_URL: mongodb://...
    ports:
      - 3000:3000