
version: '2'

services:
  stickerapp:
    image: stickerapp:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      MONGODB_URL: mongodb://...
    ports:
      - 3000:3000
      - 5858:5858
    command: node --debug=5858 server/index.js